import '../scss/style.scss';
/*import '../scss/null/null.scss';
import '../scss/header/header.scss';
import '../scss/main/about-block/about-block.scss';*/
import "../js/sliders/brends/swiper.min.js";
import '../js/sliders/brends/brends.js';
import "../js/sliders/equipment/script.js";
import "../js/sliders/price/price.js";
import '../js/burger/burger.js';
import "../js/form/call/call.js";
import "../js/form/feedback/feedback.js";